//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanetTelex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanetTelex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid property to sort on. It doesn&apos;t exist in the Class..
        /// </summary>
        internal static string CompareArgumentException {
            get {
                return ResourceManager.GetString("CompareArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send message &apos;{0}&apos; from {1} to {2}..
        /// </summary>
        internal static string EmailMessageNotSent {
            get {
                return ResourceManager.GetString("EmailMessageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message &apos;{0}&apos; from {1} to {2} has been sent..
        /// </summary>
        internal static string EmailMessageSent {
            get {
                return ResourceManager.GetString("EmailMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid fraction.  Fractions must be of the format: a/b.
        /// </summary>
        internal static string FractionToDoubleArgumentException {
            get {
                return ResourceManager.GetString("FractionToDoubleArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate embedded resource &apos;{0}&apos; in assembly &apos;{1}&apos;.
        /// </summary>
        internal static string GetEmbeddedFileFileNotFoundException {
            get {
                return ResourceManager.GetString("GetEmbeddedFileFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index plus count exceeds the size of the string..
        /// </summary>
        internal static string IndexPlusCountExceedsSize {
            get {
                return ResourceManager.GetString("IndexPlusCountExceedsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is not a valid http URI..
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map into a null object..
        /// </summary>
        internal static string MapObjectArgumentNullException1 {
            get {
                return ResourceManager.GetString("MapObjectArgumentNullException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type parameters cannot be null..
        /// </summary>
        internal static string MapObjectArgumentNullException2 {
            get {
                return ResourceManager.GetString("MapObjectArgumentNullException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MimeTypeAttribute supplied for FileExtension..
        /// </summary>
        internal static string MimeTypeNotFound {
            get {
                return ResourceManager.GetString("MimeTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml did not contain any text or CData nodes..
        /// </summary>
        internal static string NoTextOrCDataInXml {
            get {
                return ResourceManager.GetString("NoTextOrCDataInXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the suffix string cannot be greater than the desired length..
        /// </summary>
        internal static string ShortenArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("ShortenArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type {0} does not contain property: {1}.
        /// </summary>
        internal static string SortArgumentException1 {
            get {
                return ResourceManager.GetString("SortArgumentException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property &apos;{1}&apos; is not comparable..
        /// </summary>
        internal static string SortArgumentException2 {
            get {
                return ResourceManager.GetString("SortArgumentException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither objects, nor objects type can be null..
        /// </summary>
        internal static string SortArgumentNullException1 {
            get {
                return ResourceManager.GetString("SortArgumentNullException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither objects, objects type, nor sortByProperty can be null..
        /// </summary>
        internal static string SortArgumentNullException2 {
            get {
                return ResourceManager.GetString("SortArgumentNullException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day ago.
        /// </summary>
        internal static string TimeAgoADay {
            get {
                return ResourceManager.GetString("TimeAgoADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        internal static string TimeAgoAMinute {
            get {
                return ResourceManager.GetString("TimeAgoAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about an hour ago.
        /// </summary>
        internal static string TimeAgoAnHour {
            get {
                return ResourceManager.GetString("TimeAgoAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} hours ago.
        /// </summary>
        internal static string TimeAgoLessThanADay {
            get {
                return ResourceManager.GetString("TimeAgoLessThanADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute ago.
        /// </summary>
        internal static string TimeAgoLessThanAMinute {
            get {
                return ResourceManager.GetString("TimeAgoLessThanAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string TimeAgoLessThanAnHour {
            get {
                return ResourceManager.GetString("TimeAgoLessThanAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string TimeAgoMoreThanADay {
            get {
                return ResourceManager.GetString("TimeAgoMoreThanADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string TimeAgoMoreThanAMonth {
            get {
                return ResourceManager.GetString("TimeAgoMoreThanAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year {0} months and {1} days ago.
        /// </summary>
        internal static string TimeAgoMoreThanAYear {
            get {
                return ResourceManager.GetString("TimeAgoMoreThanAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years {1} months and {2} days ago.
        /// </summary>
        internal static string TimeAgoMoreThanTwoYears {
            get {
                return ResourceManager.GetString("TimeAgoMoreThanTwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPod, iPad, iPhone, iMac.
        /// </summary>
        internal static string TitleCaseToCase {
            get {
                return ResourceManager.GetString("TitleCaseToCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the, of, or, and, an, a, in, is, are, to, on, with.
        /// </summary>
        internal static string TitleCaseToLower {
            get {
                return ResourceManager.GetString("TitleCaseToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type provided must be an Enum..
        /// </summary>
        internal static string TypeNotEnum {
            get {
                return ResourceManager.GetString("TypeNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
